language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
before_script:
  - npm install
script:
  - ajv compile -s json-spec/json-schema/stac-item.json -r json-spec/json-schema/geojson.json
  # - swagger-cli validate api-spec/STAC-fragment.yaml
  - swagger-cli validate api-spec/STAC-standalone-swagger2.yaml
  - swagger-cli validate api-spec/STAC-standalone.yaml
  - swagger-cli validate api-spec/WFS3core+STAC-swagger2.yaml
  - swagger-cli validate api-spec/WFS3core+STAC.yaml
