version: 2
jobs:
  test_examples:
    working_directory: ~/stac
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - run:
          name: install
          command: pip install stac-validator
      - run:
          name: validate
          command: |
            stac_validator catalog-spec/examples/catalog.json
            stac_validator collection-spec/examples/sentinel2.json
            stac_validator item-spec/examples/sample.json
            stac_validator item-spec/examples/sample-full.json
            stac_validator item-spec/examples/sentinel2-sample.json
            stac_validator item-spec/examples/planet-sample.json
            stac_validator item-spec/examples/landsat8-sample.json
            stac_validator item-spec/examples/digitalglobe-sample.json
            stac_validator item-spec/examples/CBERS_4_MUX_20181029_177_106_L4.json
  test_docs:
    working_directory: ~/stac
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: validate
          command: npm run check-markdown
workflows:
  version: 2
  test:
    jobs:
      - test_examples
      - test_docs