version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4

    working_directory: ~/stac

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: v2-python-requirements-{{ checksum "requirements.txt" }}
      - run:
          name: install
          command: |
            git clone git@github.com:sparkgeo/stac-validator.git ~/stac-validator
            cd ~/stac-validator
            pip install -r requirements.txt
            pip install .
      - save_cache:
          key: v2-python-requirements-{{ checksum "requirements.txt" }}
          paths:
            - "~/.cache/pip"
            - "/usr/local/lib/python3.6/site-packages"
      - run:
          name: validate
          command: |
            stac_validator catalog-spec/examples/catalog.json
            stac_validator collection-spec/examples/sentinel2.json
            stac_validator item-spec/examples/sample.json
            stac_validator item-spec/examples/sample-full.json
            stac_validator item-spec/examples/sentinel2-sample.json
            stac_validator item-spec/examples/planet-sample.json
            stac_validator item-spec/examples/landsat8-sample.json
            stac_validator item-spec/examples/digitalglobe-sample.json
            stac_validator item-spec/examples/CBERS_4_MUX_20181029_177_106_L4.json
